version: '3.9'

services:
  sharpdevmind.api:
    image: ${DOCKER_REGISTRY-}sharpdevmindapi
    container_name: SharpDevMind.Api
    build:
      context: .
      dockerfile: src/Api/SharpDevMind.Api/Dockerfile
    ports:
        - 7000:8080
        - 7001:8081  
  
  sharpdevmind.database:
    image: postgres:latest
    container_name: SharpDevMind.Database
    environment:
      - POSTGRES_DB=sharpdevmind
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
  sharpdevmind.seq:
    image: datalust/seq:latest
    container_name: SharpDevMind.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  sharpdevmind.redis:
    image: redis:latest
    container_name: SharpDevMind.Redis
    restart: always
    ports:
      - 6379:6379

  sharpdevmind.identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: SharpDevMind.Identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080
